/*
 * Peter Horne-Deus
 * This program calculates the number of ways a number of objects can be choosen by a set of objects
 * NChooseR.java
 * March 24, 2020
 */

package nchooser;

/**
 *
 * @author Peter
 */
public class NChooseR extends javax.swing.JFrame {

    /**
     * Creates new form NChooseR
     */
    public NChooseR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        infoLbl1 = new javax.swing.JLabel();
        infoLbl2 = new javax.swing.JLabel();
        rLbl = new javax.swing.JLabel();
        nLbl = new javax.swing.JLabel();
        nInputTxtFeild = new javax.swing.JTextField();
        rInputTxtFeild = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        outputLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLbl.setText("N Choose R");
        jPanel1.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        infoLbl1.setText("This program calculates the number of ways R objects ");
        jPanel1.add(infoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        infoLbl2.setText("can be chosen from a set of n objects");
        jPanel1.add(infoLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        rLbl.setText("Enter the number of r objects to choose");
        jPanel1.add(rLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        nLbl.setText("Enter the number of n objects to choose from");
        jPanel1.add(nLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(nInputTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 60, -1));
        jPanel1.add(rInputTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 60, -1));

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        outputLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(outputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        //User inputed variables
        int r = Integer.parseInt(rInputTxtFeild.getText());
        int n = Integer.parseInt(nInputTxtFeild.getText());
        
        //Ensuring proper inputs
        if(r == 0){
          outputLbl.setText("Cannot Calculate");  
        }
        //Showing output
        else{
            outputLbl.setText("N choose R: " + choose(n,r)+ " Ways");
        }
    }//GEN-LAST:event_calculateBtnActionPerformed
    
    /**
     * This method calculates the output for the program
     * @param n
     * @param r
     * @return 
     */
    public static int choose(int n, int r){
        //Ensuring possible inputs
        if(n == 0){
            return 0;
        }
        else if(r == 0){
            return 0;
        }
        //Returning the output
        else{
            return (fact(n) / (fact(r) * fact(n-r)));
        }
    }
    
    /**
     * This method finds the factorial of a given number
     * @param k
     * @return 
     */
    public static int fact(int k){
        //Returning a 1 value for when k has been cycled down to 1 or is initially 1 or 0
        if(k == 0 || k == 1){
            return 1;
        }
        //Cycling down the given number and calculating the factorial
        else{
            return (k*fact(k -1));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NChooseR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NChooseR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel infoLbl1;
    private javax.swing.JLabel infoLbl2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nInputTxtFeild;
    private javax.swing.JLabel nLbl;
    private javax.swing.JLabel outputLbl;
    private javax.swing.JTextField rInputTxtFeild;
    private javax.swing.JLabel rLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
